# Generated by Django 6.0.1 on 2026-03-12 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='productbarcode',
            new_name='products_pr_product_ffac94_idx',
            old_name='products_pr_product_d7f36a_idx',
        ),
        migrations.RenameIndex(
            model_name='productbarcode',
            new_name='products_pr_is_acti_6f35fd_idx',
            old_name='products_pr_is_acti_b8d8b1_idx',
        ),
        migrations.RenameIndex(
            model_name='productimage',
            new_name='products_pr_product_3d7874_idx',
            old_name='products_pr_product_2c4a3e_idx',
        ),
        migrations.RenameIndex(
            model_name='productimage',
            new_name='products_pr_is_acti_51d8ed_idx',
            old_name='products_pr_is_acti_9f2c4d_idx',
        ),
        migrations.RenameIndex(
            model_name='products',
            new_name='products_pr_is_acti_408fea_idx',
            old_name='products_pr_is_acti_4a8e2f_idx',
        ),
        migrations.RenameIndex(
            model_name='productsaveduser',
            new_name='products_pr_product_e4033e_idx',
            old_name='products_pr_product_8a5f2e_idx',
        ),
        migrations.RenameIndex(
            model_name='productsaveduser',
            new_name='products_pr_user_id_8e5296_idx',
            old_name='products_pr_user_id_3c1a4d_idx',
        ),
        migrations.RenameIndex(
            model_name='productsaveduser',
            new_name='products_pr_is_acti_f65b04_idx',
            old_name='products_pr_is_acti_1e9b2a_idx',
        ),
    ]
