# Generated by Django 5.2.6 on 2026-03-14 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_options_and_more'),
        ('products', '0002_rename_products_pr_product_d7f36a_idx_products_pr_product_ffac94_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='badge',
            options={'ordering': ['name'], 'verbose_name': 'Бейдж', 'verbose_name_plural': 'Бейджи'},
        ),
        migrations.AlterModelOptions(
            name='productsaveduser',
            options={'ordering': ['-created_at'], 'verbose_name': 'Сохранённый продукт', 'verbose_name_plural': 'Сохранённые продукты'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['name'], 'verbose_name': 'Единица измерения', 'verbose_name_plural': 'Единицы измерения'},
        ),
        migrations.AddField(
            model_name='badge',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Удалён'),
        ),
        migrations.AddField(
            model_name='productbarcode',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Удалён'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Удалён'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='products',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Удалён'),
        ),
        migrations.AddField(
            model_name='unit',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Удалён'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Активный'),
        ),
        migrations.AlterField(
            model_name='productbarcode',
            name='barcode',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Штрихкод'),
        ),
        migrations.AlterField(
            model_name='products',
            name='badge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.badge', verbose_name='Бейдж'),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='categories.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='products',
            name='discount_percentage',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Процент скидки'),
        ),
        migrations.AlterField(
            model_name='products',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Активный'),
        ),
        migrations.AlterField(
            model_name='products',
            name='is_discount',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Есть скидка'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена со скидкой'),
        ),
        migrations.AlterField(
            model_name='products',
            name='quantity',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='products',
            name='unique_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Уникальный ID'),
        ),
        migrations.AlterField(
            model_name='products',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.unit', verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='productsaveduser',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Активный'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Активный'),
        ),
    ]
