# Generated by Django 5.2.6 on 2026-03-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_badge_unit_translations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstranslation',
            name='expiration_date',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Срок годности'),
        ),
    ]
