# Generated by Django 5.2.6 on 2026-04-20 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_alter_category_home_order'),
        ('products', '0005_alter_productstranslation_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='shelf_location',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Место на полке'),
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['shelf_location'], name='products_pr_shelf_l_ea4112_idx'),
        ),
    ]
