# Generated by Django 5.2.6 on 2026-04-30 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_products_shelf_location_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productbarcode',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('barcode',), name='uniq_active_product_barcode'),
        ),
    ]
