# Generated by Django 5.0.7 on 2026-05-15 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productbarcode_uniq_active_product_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='sale_unit',
            field=models.CharField(choices=[('piece', 'Piece'), ('weight', 'Weight (kg)')], db_index=True, default='piece', help_text='piece — целое кол-во (шт); weight — дробный вес (кг), в корзине добавляется buffer на заказ.', max_length=16, verbose_name='Тип продажи'),
        ),
    ]
