# Generated by Django 6.0.1 on 2026-05-17 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_unit_and_unit_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_unit',
            field=models.CharField(choices=[('piece', 'piece — Штука (dona)'), ('kg', 'kg — Килограмм (kg)'), ('gram', 'gram — Грамм (g)'), ('liter', 'liter — Литр (l)'), ('ml', 'ml — Миллилитр (ml)')], db_index=True, default='piece', help_text='Цена в price за unit_amount этой единицы (kg, ml, piece, …).', max_length=16, verbose_name='Единица цены'),
        ),
        migrations.AlterField(
            model_name='products',
            name='sale_unit',
            field=models.CharField(choices=[('piece', 'Piece'), ('weight', 'Weight (kg)')], db_index=True, default='piece', help_text='Устаревшее: синхронизируется с product_unit. piece / weight.', max_length=16, verbose_name='Тип продажи'),
        ),
    ]
