# Generated by Django 5.2.6 on 2026-03-14 05:54

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_orders_order_user_id_idx_orders_orde_user_id_a87c6f_idx_and_more'),
        ('products', '0002_rename_products_pr_product_d7f36a_idx_products_pr_product_ffac94_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ordercourier',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='order',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Удалён'),
        ),
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='Примечания'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Общая сумма'),
        ),
        migrations.AddField(
            model_name='ordercourier',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Завершён'),
        ),
        migrations.AddField(
            model_name='ordercourier',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='Примечания'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Цена за единицу'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('process', 'В обработке'), ('delivering', 'Доставляется'), ('completed', 'Выполнен'), ('rejected', 'Отменён')], db_index=True, default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='ordercourier',
            name='courier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_orders', to=settings.AUTH_USER_MODEL, verbose_name='Курьер'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_products', to='products.products', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Сумма'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='orders_orde_created_0e92de_idx'),
        ),
        migrations.AddIndex(
            model_name='ordercourier',
            index=models.Index(fields=['order'], name='orders_orde_order_i_66a2ea_idx'),
        ),
        migrations.AddIndex(
            model_name='ordercourier',
            index=models.Index(fields=['courier'], name='orders_orde_courier_de00a8_idx'),
        ),
        migrations.AddIndex(
            model_name='orderproduct',
            index=models.Index(fields=['order'], name='orders_orde_order_i_d30f9b_idx'),
        ),
        migrations.AddIndex(
            model_name='orderproduct',
            index=models.Index(fields=['product'], name='orders_orde_product_eebe32_idx'),
        ),
        migrations.RemoveField(
            model_name='ordercourier',
            name='updated_at',
        ),
    ]
