# Generated by Django 5.2.6 on 2026-04-20 14:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_ordercourier_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderFeeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_fee_percent', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5)),
                ('packing_fee_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройки сборов',
                'verbose_name_plural': 'Настройки сборов',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='apartment',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Дом/квартира'),
        ),
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Доставка'),
        ),
        migrations.AddField(
            model_name='order',
            name='entrance',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Подъезд'),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Оценочная сумма'),
        ),
        migrations.AddField(
            model_name='order',
            name='final_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Итоговая сумма (admin)'),
        ),
        migrations.AddField(
            model_name='order',
            name='packing_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Пакет/сбор'),
        ),
        migrations.AddField(
            model_name='order',
            name='products_subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Сумма товаров'),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Сумма возврата'),
        ),
        migrations.AddField(
            model_name='order',
            name='service_fee_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Сервисный сбор'),
        ),
        migrations.AddField(
            model_name='order',
            name='service_fee_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Сервисный процент'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Yangi'), ('picking', 'Yig‘ilyapti'), ('on_the_way', 'Yo‘lda'), ('delivered', 'Yetkazildi'), ('rejected', 'Отменён'), ('cancelled', 'Отменён пользователем')], db_index=True, default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='DeliveryFeeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_order_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('max_order_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Правило доставки',
                'verbose_name_plural': 'Правила доставки',
                'ordering': ['min_order_amount', 'id'],
                'indexes': [models.Index(fields=['is_active', 'min_order_amount'], name='orders_deli_is_acti_863c8e_idx')],
            },
        ),
    ]
