# Generated by Django 5.0.7 on 2026-05-14 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderfeesettings_order_apartment_order_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Дата доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_time_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Конец интервала доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_time_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Начало интервала доставки'),
        ),
        migrations.CreateModel(
            name='BusySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Дата')),
                ('start_time', models.TimeField(verbose_name='Начало')),
                ('end_time', models.TimeField(verbose_name='Конец')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Занятый слот',
                'verbose_name_plural': 'Занятые слоты',
                'ordering': ['date', 'start_time', 'id'],
                'indexes': [models.Index(fields=['date'], name='orders_busy_date_6114c2_idx')],
            },
        ),
    ]
