# Generated by Django 5.0.7 on 2026-05-14 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_busy_slot_and_order_delivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusyDayWorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True, verbose_name='Дата')),
                ('working_start', models.TimeField(verbose_name='Начало рабочего дня')),
                ('working_end', models.TimeField(verbose_name='Конец рабочего дня')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Рабочие часы дня (доставка)',
                'verbose_name_plural': 'Рабочие часы по дням',
                'ordering': ['-date', 'id'],
            },
        ),
    ]
