# Generated by Django 5.0.7 on 2026-05-15 01:42

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def forwards_migrate_order_status(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')
    Order.objects.filter(status='new').update(status='created')
    Order.objects.filter(status='on_the_way').update(status='shipped')


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_busy_day_working_hours'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='buffer_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Буфер по весу'),
        ),
        migrations.AddField(
            model_name='order',
            name='leave_at_door',
            field=models.BooleanField(default=False, verbose_name='Оставить у двери'),
        ),
        migrations.AddField(
            model_name='order',
            name='loyalty_discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Скидка баллами'),
        ),
        migrations.AddField(
            model_name='order',
            name='loyalty_points_used',
            field=models.PositiveIntegerField(default=0, verbose_name='Списано баллов'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('authorized', 'Authorized'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20, verbose_name='Оплата'),
        ),
        migrations.AddField(
            model_name='orderfeesettings',
            name='loyalty_point_currency_value',
            field=models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=12, verbose_name='Сумма за 1 балл (UZS)'),
        ),
        migrations.AddField(
            model_name='orderfeesettings',
            name='min_order_subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('40000.00'), max_digits=14, verbose_name='Мин. сумма товаров для оформления'),
        ),
        migrations.AddField(
            model_name='orderfeesettings',
            name='weight_buffer_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, verbose_name='Буфер по весу, %'),
        ),
        migrations.RunPython(forwards_migrate_order_status, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('confirmed', 'Confirmed'), ('picking', 'Picking'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled (user)')], db_index=True, default='created', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='quantity',
            field=models.DecimalField(decimal_places=3, help_text='Шт (целое) или кг (дробное) в зависимости от продукта.', max_digits=12, verbose_name='Количество'),
        ),
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='', max_length=100, verbose_name='Подпись')),
                ('street', models.CharField(max_length=255, verbose_name='Улица / район')),
                ('house_number', models.CharField(blank=True, default='', max_length=50, verbose_name='Дом')),
                ('apartment', models.CharField(blank=True, default='', max_length=50, verbose_name='Квартира')),
                ('entrance', models.CharField(blank=True, default='', max_length=50, verbose_name='Подъезд')),
                ('floor', models.CharField(blank=True, default='', max_length=20, verbose_name='Этаж')),
                ('intercom_code', models.CharField(blank=True, default='', max_length=50, verbose_name='Домофон')),
                ('lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Широта')),
                ('long', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Долгота')),
                ('is_default', models.BooleanField(db_index=True, default=False, verbose_name='По умолчанию')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_addresses', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Адрес доставки',
                'verbose_name_plural': 'Адреса доставки',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.deliveryaddress', verbose_name='Адрес доставки'),
        ),
        migrations.CreateModel(
            name='DeliverySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_date', models.DateField(db_index=True, verbose_name='Дата')),
                ('start_time', models.TimeField(verbose_name='Начало')),
                ('end_time', models.TimeField(verbose_name='Конец')),
                ('capacity', models.PositiveIntegerField(default=30, verbose_name='Макс. заказов')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Доставка в слоте')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Слот доставки',
                'verbose_name_plural': 'Слоты доставки',
                'ordering': ['slot_date', 'start_time', 'id'],
                'indexes': [models.Index(fields=['slot_date', 'is_active'], name='orders_deli_slot_da_80f398_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='deliveryslot',
            constraint=models.UniqueConstraint(fields=('slot_date', 'start_time', 'end_time'), name='uniq_delivery_slot_window'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.deliveryslot', verbose_name='Слот доставки'),
        ),
        migrations.AddIndex(
            model_name='deliveryaddress',
            index=models.Index(fields=['user', '-updated_at'], name='orders_deli_user_id_232355_idx'),
        ),
    ]
