# Generated by Django 6.0.1 on 2026-05-15 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_clickpayment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='clickpayment',
            new_name='orders_clic_order_i_bd019e_idx',
            old_name='orders_clic_order_i_idx',
        ),
    ]
