# Generated by Django 6.0.1 on 2026-05-17 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_cancel_reasons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='quantity',
            field=models.DecimalField(decimal_places=3, help_text='Miqdor (product_unit bo‘yicha).', max_digits=12, verbose_name='Количество'),
        ),
    ]
