# Generated by Django 6.0.1 on 2026-05-25 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_order_status_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryaddress',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='long',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='order',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='order',
            name='long',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True, verbose_name='Долгота'),
        ),
    ]
