# Generated by Django 5.0.7 on 2026-06-11 14:06

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_clickrefund'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashbackSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cashback_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Cashback, %')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройки cashback',
                'verbose_name_plural': 'Настройки cashback',
            },
        ),
        migrations.CreateModel(
            name='CashbackTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Сумма (UZS)')),
                ('transaction_type', models.CharField(choices=[('earned', 'Начисление'), ('reversed', 'Списание')], db_index=True, max_length=20)),
                ('balance_after', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Баланс после')),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Cashback транзакция',
                'verbose_name_plural': 'Cashback транзакции',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='Название')),
                ('address', models.TextField(verbose_name='Адрес / описание')),
                ('lat', models.DecimalField(decimal_places=18, max_digits=21, verbose_name='Широта (центр)')),
                ('long', models.DecimalField(decimal_places=18, max_digits=21, verbose_name='Долгота (центр)')),
                ('radius_m', models.PositiveIntegerField(help_text='Buyurtma faqat shu radius ichida ochiladi.', verbose_name='Радиус (м)')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Зона доставки',
                'verbose_name_plural': 'Зоны доставки',
                'ordering': ['-is_active', '-updated_at', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-id'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.RenameIndex(
            model_name='clickrefund',
            new_name='orders_clic_order_i_d6fc90_idx',
            old_name='orders_clic_order_i_4a8b2d_idx',
        ),
        migrations.AddField(
            model_name='order',
            name='cashback_earned',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Начисленный cashback'),
        ),
        migrations.AddField(
            model_name='cashbacktransaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashback_transactions', to='orders.order', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='cashbacktransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashback_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddIndex(
            model_name='deliveryzone',
            index=models.Index(fields=['is_active', '-updated_at'], name='orders_deli_is_acti_dce1f5_idx'),
        ),
        migrations.AddIndex(
            model_name='cashbacktransaction',
            index=models.Index(fields=['user', '-created_at'], name='orders_cash_user_id_69e2a0_idx'),
        ),
        migrations.AddIndex(
            model_name='cashbacktransaction',
            index=models.Index(fields=['order', 'transaction_type'], name='orders_cash_order_i_37fa78_idx'),
        ),
    ]
