# Generated by Django 6.0.1 on 2026-03-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userdevice'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userdevice',
            new_name='accounts_us_user_id_8c51a6_idx',
            old_name='accounts_us_user_id_77e4e0_idx',
        ),
        migrations.RenameIndex(
            model_name='userdevice',
            new_name='accounts_us_is_acti_59e8d2_idx',
            old_name='accounts_us_is_acti_5c9e36_idx',
        ),
        migrations.AddIndex(
            model_name='phoneotp',
            index=models.Index(fields=['phone'], name='accounts_ph_phone_bc4927_idx'),
        ),
        migrations.AddIndex(
            model_name='phoneotp',
            index=models.Index(fields=['is_verified'], name='accounts_ph_is_veri_a5cad4_idx'),
        ),
    ]
