# Generated by Django 5.2.6 on 2026-03-14 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_accounts_us_user_id_77e4e0_idx_accounts_us_user_id_8c51a6_idx_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='phoneotp',
            name='accounts_ph_phone_bc4927_idx',
        ),
        migrations.RemoveIndex(
            model_name='phoneotp',
            name='accounts_ph_is_veri_a5cad4_idx',
        ),
        migrations.RemoveIndex(
            model_name='userdevice',
            name='accounts_us_user_id_8c51a6_idx',
        ),
        migrations.RemoveIndex(
            model_name='userdevice',
            name='accounts_us_is_acti_59e8d2_idx',
        ),
        migrations.AlterUniqueTogether(
            name='userdevice',
            unique_together={('user', 'device_token')},
        ),
        migrations.AddField(
            model_name='phoneotp',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Попытки'),
        ),
        migrations.AddField(
            model_name='userdevice',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Подтвержден'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='phoneotp',
            name='code',
            field=models.CharField(max_length=6, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='phoneotp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='phoneotp',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Подтвержден'),
        ),
        migrations.AlterField(
            model_name='phoneotp',
            name='phone',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='userdevice',
            name='device_type',
            field=models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web')], max_length=20, verbose_name='Тип устройства'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['created_at'], name='accounts_cu_created_35a2d8_idx'),
        ),
        migrations.AddIndex(
            model_name='phoneotp',
            index=models.Index(fields=['phone', 'code'], name='accounts_ph_phone_373c3c_idx'),
        ),
        migrations.AddIndex(
            model_name='phoneotp',
            index=models.Index(fields=['created_at'], name='accounts_ph_created_fa03f2_idx'),
        ),
        migrations.AddIndex(
            model_name='userdevice',
            index=models.Index(fields=['user', 'is_active'], name='accounts_us_user_id_054818_idx'),
        ),
        migrations.AddIndex(
            model_name='userdevice',
            index=models.Index(fields=['device_token'], name='accounts_us_device__ad070e_idx'),
        ),
        migrations.RemoveField(
            model_name='userdevice',
            name='is_activate',
        ),
    ]
