# Generated by Django 5.0.7 on 2026-05-15 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_phoneotp_accounts_ph_phone_bc4927_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='loyalty_points',
            field=models.PositiveIntegerField(default=0, help_text='Списание при оформлении заказа; не более 50% суммы заказа (см. pricing).', verbose_name='Баллы лояльности'),
        ),
    ]
