# Generated by Django 5.0.7 on 2026-06-11 14:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_korzinka_checkout_v1'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cashback_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Накопительный cashback (UZS)'),
        ),
    ]
