# Generated by Django 5.2.6 on 2026-03-14 05:37

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        # MUHIM: Avval unique_together o'chiriladi, keyin field
        migrations.AlterUniqueTogether(
            name='poststranslation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='poststranslation',
            name='master',
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активный')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Удалён')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active', 'is_deleted'], name='news_post_is_acti_b27ae1_idx'), models.Index(fields=['created_at'], name='news_post_created_e546b5_idx'), models.Index(fields=['published_at'], name='news_post_publish_4ef118_idx')],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Удалён')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('image', models.ImageField(upload_to='posts/images/', verbose_name='Изображение')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Подпись')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='news.post', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'Изображение поста',
                'verbose_name_plural': 'Изображения поста',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Контент')),
                ('short_description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Краткое описание')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='news.post')),
            ],
            options={
                'verbose_name': 'Пост Translation',
                'db_table': 'news_post_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.DeleteModel(
            name='PostImages',
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
        migrations.DeleteModel(
            name='PostsTranslation',
        ),
        migrations.AddIndex(
            model_name='postimage',
            index=models.Index(fields=['post'], name='news_postim_post_id_ea6d60_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='posttranslation',
            unique_together={('language_code', 'master')},
        ),
    ]
