# Generated by Django 5.2.6 on 2026-03-24 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='home_order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок на главной странице'),
        ),
    ]
