# Generated by Django 5.2.6 on 2026-03-24 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_category_home_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='home_order',
            field=models.PositiveIntegerField(blank=True, db_index=True, default=0, null=True, verbose_name='Порядок на главной странице'),
        ),
    ]
