# Generated by Django 5.2.6 on 2026-04-30 18:15

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0007_productbarcode_uniq_active_product_barcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('contact_person', models.CharField(blank=True, default='', max_length=255)),
                ('inn', models.CharField(blank=True, default='', max_length=50)),
                ('address', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_number', models.CharField(db_index=True, max_length=50)),
                ('doc_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('posted', 'Проведен'), ('cancelled', 'Отменен')], db_index=True, default='draft', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_receipts', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='inventory.supplier')),
            ],
            options={
                'verbose_name': 'Приход',
                'verbose_name_plural': 'Приходы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('purchase_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('sell_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('margin_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('product_name_snapshot', models.CharField(blank=True, default='', max_length=255)),
                ('barcode_snapshot', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_items', to='products.products')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stockreceipt')),
            ],
            options={
                'verbose_name': 'Товар прихода',
                'verbose_name_plural': 'Товары прихода',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['receipt'], name='inventory_s_receipt_b510d8_idx'), models.Index(fields=['product'], name='inventory_s_product_416b26_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='stockreceipt',
            index=models.Index(fields=['supplier', 'doc_date'], name='inventory_s_supplie_761060_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreceipt',
            index=models.Index(fields=['status'], name='inventory_s_status_18e6cb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stockreceipt',
            unique_together={('doc_number',)},
        ),
    ]
