# Generated by Django 5.0.7 on 2026-06-11 14:10

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockreceipt',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Отменён'),
        ),
        migrations.AddField(
            model_name='stockreceipt',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockreceipt',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Проведён'),
        ),
        migrations.AddField(
            model_name='stockreceipt',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posted_receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SupplierReconciliationAct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_from', models.DateField(db_index=True, verbose_name='Период с')),
                ('period_to', models.DateField(db_index=True, verbose_name='Период по')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Начальный остаток (долг)')),
                ('receipts_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Сумма приходов за период')),
                ('receipts_count', models.PositiveIntegerField(default=0, verbose_name='Кол-во приходов')),
                ('closing_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Конечный остаток')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('confirmed', 'Подтверждён')], db_index=True, default='draft', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_reconciliation_acts', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_reconciliation_acts', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_acts', to='inventory.supplier')),
            ],
            options={
                'verbose_name': 'Акт сверки',
                'verbose_name_plural': 'Акты сверки',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['supplier', 'period_from', 'period_to'], name='inventory_s_supplie_4e2c32_idx'), models.Index(fields=['status', '-created_at'], name='inventory_s_status_92927c_idx')],
            },
        ),
    ]
