# Generated by Django 5.0.7 on 2026-07-23 18:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_warehouse_reconciliation'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockreceipt',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='stockreceipt',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Оплачено'),
        ),
        migrations.AddField(
            model_name='stockreceiptitem',
            name='update_catalog_price',
            field=models.BooleanField(default=False, help_text='При проведении обновить Products.price = sell_price', verbose_name='Изменить тек. цену'),
        ),
        migrations.AlterField(
            model_name='stockreceipt',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Сумма'),
        ),
    ]
